{
  "comments": [
    {
      "key": {
        "uuid": "1a6eadb0_de8f7921",
        "filename": "tests/test_script.py",
        "patchSetId": 3
      },
      "lineNbr": 27,
      "author": {
        "id": 679
      },
      "writtenOn": "2016-12-13T17:43:02Z",
      "side": 1,
      "message": "This doesn\u0027t smell right; if the assert fails, it outputs .data as the error message, which, while perhaps useful, feels like it could be a bit confusing.  Also, there\u0027s the whole \u0027in\u0027 test inside an assertTrue(); with the way we\u0027re constructing JenkinsTestBase, we should have access to the assertIn() method here, which would probably be the superior way to go.",
      "revId": "4cecde2b83fd7609908cd9fd4f43504e842643fb",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}