{
  "comments": [
    {
      "key": {
        "uuid": "9a80dd14_4e44071b",
        "filename": "tests/test_jenkins.py",
        "patchSetId": 5
      },
      "lineNbr": 1158,
      "author": {
        "id": 2475
      },
      "writtenOn": "2015-03-18T10:55:41Z",
      "side": 1,
      "message": "Thanks for the test! The get_nodes() method catch three different exceptions and raise two. That is not covered!\n\nI am adding appropriate tests to fullfill the coverage in next patchset.",
      "revId": "530d4acde7dc1accb2518ab856ac25e5408561b8",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}